### ISSUE TITLE
bing翻译未知错误了

### ISSUE THREAD

**Issue by youwillbe** [bilibili-ayang/bob-plugin-free-bing-translate#1]
RT

**Comment by youwillbe** [comment]
[你这是多写了个t吧？](https://github.com/bilibili-ayang/bob-plugin-free-bing-translate/blob/11a09c59db5ef97d36190872cbe6960695dc5ea9/server/app.js#LL51C24-L51C36)

**Comment by ayangweb** [comment]
> [你这是多写了个t吧？](https://github.com/bilibili-ayang/bob-plugin-free-bing-translate/blob/11a09c59db5ef97d36190872cbe6960695dc5ea9/server/app.js#LL51C24-L51C36)

建议你先试过插件之后再提 issues！

**Comment by youwillbe** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/16474244/227121230-50c2e7d7-43d9-4fba-a11f-baefa213036e.png">
肯定是用过了啊，还能忽悠你咋滴。。。

**Comment by ayangweb** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/75017711/227122352-84a538ce-99f4-416c-9896-64258f29886c.png">

**Comment by ayangweb** [comment]
> <img alt="image" width="399" src="https://user-images.githubusercontent.com/16474244/227121230-50c2e7d7-43d9-4fba-a11f-baefa213036e.png">
> 
> 肯定是用过了啊，还能忽悠你咋滴。。。

你下载的是最新版本吗？

**Comment by youwillbe** [comment]
是的呢
<img width="705" alt="image" src="https://user-images.githubusercontent.com/16474244/227123235-759bc481-e610-4837-9460-6f6fe8e03a29.png">

**Comment by ayangweb** [comment]
这就尴尬了，我这边是正常的！

**Comment by youwillbe** [comment]
可能是网络问题吧，没事，你忙
