### ISSUE TITLE
你好，4/19使用好像出现"未知错误" 无法翻译

### ISSUE THREAD

**Issue by BravoiOS** [bilibili-ayang/bob-plugin-free-bing-translate#2]

**Comment by ayangweb** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/75017711/232981492-fb450c81-e3db-4d6f-bd38-845cb90366ce.png">

我这边测试没问题，方便截图或者把你发的翻译内容给我！

**Comment by BravoiOS** [comment]
你好，请参考附图：）
<img width="455" alt=" 2023-04-19 15 28 40" src="https://user-images.githubusercontent.com/7866559/233001242-5e760e55-e4ee-45ca-8574-9d08175ce479.png">
<img width="463" alt=" 2023-04-19 15 27 57" src="https://user-images.githubusercontent.com/7866559/233001291-b59e828d-18d9-4b18-907d-7ec480e0931f.png">

**Comment by ayangweb** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/75017711/233004495-9688c32b-f18b-4ebc-865d-f0c953b18fc7.png">

我这边没问题，真奇怪

**Comment by BravoiOS** [comment]
会不会区域保护限制？我不在国内，但我刚翻回国内，就使用正常了
尝试到其他国家，也都出现错误

**Comment by ayangweb** [comment]
> 会不会区域保护限制？我不在国内，但我刚翻回国内，就使用正常了 尝试到其他国家，也都出现错误

不好说，有可能，你试试必应翻译官网行不行，我翻到国外也是正常的！

**Comment by BravoiOS** [comment]
必应翻译官网测试下是正常的..
<img width="693" alt="CleanShot 2023-04-19 at 16 31 42@2x" src="https://user-images.githubusercontent.com/7866559/233017962-c7b9d968-98fa-4fdf-b265-2de7b0888dd1.png">

**Comment by ayangweb** [comment]
> 必应翻译官网测试下是正常的..

那就奇怪了，我就用的官网接口

**Comment by BravoiOS** [comment]
只好再等看看有没有人有类似问题了
不过我用其他插件都能正常翻译，就必应出现问题，真的蛮奇怪的

**Comment by ayangweb** [comment]
> 只好再等看看有没有人有类似问题了 不过我用其他插件都能正常翻译，就必应出现问题，真的蛮奇怪的

上一条 issues 也是这个问题，但是不知道啥情况，我这边没法复现，也不好解决

**Comment by BravoiOS** [comment]
我突然想到，Bing翻译和微软翻译不知道是不是调用同个内壳？我尝试翻回国内对应两个翻译，差异好像不大，
微软翻译调用API时需要填写region : 比如eastasia，不知道是不是和这个有关？
另外我在使用沉浸式翻译 [https://github.com/immersive-translate/immersive-translate/](url) 里的Bing翻译也正常没问题，希望还是有机会能解决。

<img width="941" alt="CleanShot 2023-04-19 at 17 00 11@2x" src="https://user-images.githubusercontent.com/7866559/233024551-430e5859-0b23-445f-b77a-17e1b0a8f449.png">

**Comment by Kerwin1202** [comment]
+1

<img width="429" alt="image" src="https://github.com/ayangweb/bob-plugin-free-bing-translate/assets/16319833/5ec8aca7-0966-47bf-b1e2-47be9ede2f16">

**Comment by crown789** [comment]
我测试这个如果是国内的用户 把代理设置下,让微软的api别走代理就可以了，国外的就不知道了

**Comment by ayangweb** [comment]
@BravoiOS @Kerwin1202 @crown789 非常抱歉，最近比较忙，最新版已修复！
